# this is now in alias file

UDEV_UART ?= /dev/serial/by-id/usb-FTDI_Dual_RS232-HS-if01-port0
UDEV_JTAG ?= /dev/serial/by-id/usb-FTDI_Dual_RS232-HS-if00-port0

#/dev/serial/by-path/pci-0000:00:1d.7-usb-0:2:1.0-port0
#/dev/serial/by-path/pci-0000:00:1d.7-usb-0:2:1.1-port0
